# Generated by Django 4.1.3 on 2022-11-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Titulo')),
                ('last_name', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Creado el')),
                ('password', models.CharField(max_length=128, verbose_name='Entregado el')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
